title: "Light Nite Status "
baseURL: https://status.lightnite.io
languageCode: en
params:
  shortDateFormat: 15:04 — Jan 2
  meta_description: This status page provides updated information about our
    systems' normal operation, incidents that may happen, and their resolution.
  systems:
    - name: Website
      description: Our company public facing website
      link: https://lightnite.io
    - name: Web Store
      description: Web platform to buy in-game skins from the game & referrals
      link: https://play.lightnite.io
  dateFormat: January 2, 2006 at 3:04 PM
  disqusShortname: <script id="dsq-count-scr"
    src="//https-status-lightnite-io.disqus.com/count.js" async></script>
  timezoneString: CET
  logo: https://lightnite.io/assets/img/utils/logo.png
  description_header: Information about <a class='text-grey-darkest' title='Visit
    example.com' href='https://www.lightnite.io/'>Light Nite</a> systems
    operations.<br />Follow us <a class='text-grey-darkest' title='Visit our
    page on Twitter' href='https://www.twitter.com/lightnitegame'>on Twitter</a>
    or join our <a class='text-grey-darkest' href='https://ln.onl/discord'
    >Discord</a><br />to be alerted of new events.
  copyrightHolder: Satoshis Games Inc
  eventsPerPage: 10
  iconType: image/png
  icon: /images/clearstatus.png
  description_footer: ""
